[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "hugpi"
version= "0.1.4"
authors = [
  { name="Kammari santhosh", email="your.email@example.com" },
]
description = "A LangChain integration for HuggingChat models"
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

dependencies = [
]
[project.urls]
"Homepage" = "https://github.com/yourusername"
"Bug Tracker" = "https://github.com/yourusername"

[tool.setuptools.packages.find]
where = ["src"]